language: python
fast_finish: true
dist: xenial
cache: pip

python:
- 3.6
- 3.5

install: pip install -r requirements.txt
script: pytest

stages:
- name: quality
- name: test
- name: deploy to pypi
  if: branch = master AND tag =~ /^Release.*$/

jobs:
  include:
  - name: Test and coverage using Python 3.7
    python: 3.7
    install:
    - pip install codecov
    - pip install -r requirements.txt
    env: CODECOV_TOKEN="c54d90f6-f88b-4d81-a284-2c97f6c32161"
    script: 
      - pytest -m "not integration" --cov=leaderboard --cov-config=build/.coveragerc --cov-fail-under 60
      - pytest -m integration
    after_success: codecov -F unittests
  - name: Integration test using Python 3.7.2 on macOS
    os: osx
    osx_image: xcode10.2
    language: shell
    before_install: pip3 install --upgrade pip
    script: pytest -v -m integration --cov=leaderboard --cov-config=build/.coveragerc --cov-fail-under 80
    after_success: codecov -F integration
  - name: Integration test using Python 3.7.3 on Windows
    os: windows
    language: shell
    before_install: choco install python
    env: PATH=/c/Python37:/c/Python37/Scripts:$PATH
    script: pytest -v -m integration

  - stage: quality
    name: Static code analysis and style checks 
    addons:
      sonarcloud:
        organization: "chriskn"
        token:
          secure: "452a8d35b147b591523a3744a98fab6334d33cfc"
    install:
    - pip install black
    - pip install pylint
    - pip install -r requirements.txt
    script:
    - python -m pylint leaderboard --rcfile build/.pylintrc
    - black leaderboard --diff --check
    after_success: sonar-scanner -Dproject.settings=build/sonar-project.properties

  - stage: deploy to pypi 
    install: pip install pdoc
    script: pdoc leaderboard --html --overwrite
    deploy:
      provider: pypi
      server: https://test.pypi.org/legacy/
      user: chriskn
      password: 
        secure: "es1fhT9tD9HMwSnns4PkYyUmQu40NqzXTo0gvde1/lhFKXtPo36JG9ktyoyjaMLDEuIdPcqv/uU1yvC0N7ThqipEBBTKqIF1L53OWDnMo017v1oxqsq/NNAusPybRdjx/vByRCqgh4E77NZFHRDJPXPTNYa/WuGUVd6iZhWzCi6THFqMvlhxKZjletgOj+h57kY0YrMYWH4FE1YVewDjwXWKs4qTl69btyq4HHT/uADm2di5xo9smadoK7jCW28WhoxYi9kI90o0J2WcU6/WMKtlLq6xvxH/bQX+9Hmf4M9y3fDWUZnN4aDUcgcMqvt1JyEWKyBSD3xrNTLyVydL4bCTFr2lmXjka85rxrY2XZMAxYyB0afb6sM4G8h+akzJoUJONPdjlPgMX64tsIlntdkFczUBQZJIpAQUdD9EBUsS4oYP379eKa/Mgrrv2ZfLe6zEFaPTG+gikYqziYAJMWpZAsA0akHyPAYCoQbwSwDh38EzTviDmq9V+/fhtSfYUAO1YwiFsK6okUZbmZebhXfylOau1WCINA0tWQiPqeR5Ma05CYlNNFvtbEHYgn7LZK/U+nwAux8twQy/NtAKy0mwXDEETyk4wLM5floSgxx1bQJ3T6dobrITY+W984KhFRzZD73R6xT+g48xFSFLO71MDa22kjMxjumMH4OxlPE="
      skip_existing: true
      skip_cleanup: true



notifications:
  email:
    on_success: change
    on_failure: always
