language: python
fast_finish: true
dist: xenial
cache: pip

python:
- 3.6
- 3.5

install: pip install -r requirements.txt
script: pytest

stages:
- name: quality
- name: test
- name: docs
  if: branch = master AND tag =~ /^Release.*$/

jobs:
  include:
  - name: Test and coverage using Python 3.7
    python: 3.7
    install:
    - pip install codecov
    - pip install -r requirements.txt
    env: CODECOV_TOKEN="c54d90f6-f88b-4d81-a284-2c97f6c32161"
    script: 
      - pytest -m "not integration" --cov=example --cov-config=build/.coveragerc --cov-fail-under 60
      - pytest -m integration
    after_success: codecov -F unittests
  - name: Integration test using Python 3.7.2 on macOS
    os: osx
    osx_image: xcode10.2
    language: shell
    before_install: pip3 install --upgrade pip
    script: pytest -v -m integration --cov=example --cov-config=build/.coveragerc --cov-fail-under 80
    after_success: codecov -F integration
  - name: Integration test using Python 3.7.3 on Windows
    os: windows
    language: shell
    before_install: choco install python
    env: PATH=/c/Python37:/c/Python37/Scripts:$PATH
    script: pytest -v -m integration

  - stage: quality
    name: Static code analysis and style checks 
    addons:
      sonarcloud:
        organization: "chriskn"
        token:
          secure: "452a8d35b147b591523a3744a98fab6334d33cfc"
    install:
    - pip install black
    - pip install pylint
    - pip install -r requirements.txt
    script:
    - python -m pylint example --rcfile build/.pylintrc
    - black example --diff --check
    - sonar-scanner -Dproject.settings=build/sonar-project.properties

  - stage: docs
    install: pip install pdoc
    script: pdoc example --html --overwrite

notifications:
  email:
    on_success: change
    on_failure: always
