language: python # works only for linux
dist: xenial # needed for python 3.7
cache: pip  

python:
- 3.6 # default build environment
- 3.5
- 3.7

# build script for default stage "test" 
install: pip install -r requirements.txt 
script: pytest 

jobs:
  include:
    - stage: "test"
      name: "Test with Python 3.7.2 on macOS" # see https://docs.travis-ci.com/user/reference/osx/
      os: osx  
      osx_image: xcode10.2 # macOS 10.14
      language: shell       
      before_install: pip3 install --upgrade pip
    - stage: "test"
      name: "Test with Python 3.7.3 on Windows" # see https://docs.travis-ci.com/user/reference/windows/
      os: windows # Windows 10.0.17134 N/A Build 17134
      language: shell      
      before_install: choco install python # available packages https://chocolatey.org/packages?q=python
      env: PATH=/c/Python37:/c/Python37/Scripts:$PATH
    
    - stage: "coverage"
      install:
        - pip install -r requirements.txt 
        - pip install codecov 
      env: CODECOV_TOKEN="c54d90f6-f88b-4d81-a284-2c97f6c32161"
      script: 
        - pytest --cov=example --cov-fail-under 60
        - codecov

    - stage: "quality"
      script: python -m pylint example 

    - stage: "docs"
      install: pip install pdoc
      script: pdoc example --html --overwrite

stages:
  - test
  - coverage
  - quality
  - docs
    if: branch = master AND tag =~ /^Release.*$/
